# Generated by Django 5.0.2 on 2024-04-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lieu', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now_add=True)),
                ('temp', models.CharField(max_length=10)),
                ('vent', models.CharField(max_length=10)),
                ('precepitation', models.CharField(max_length=10)),
                ('humidite', models.CharField(max_length=10)),
            ],
        ),
    ]
