# Generated by Django 5.0.2 on 2024-04-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id_wilaya', models.IntegerField(primary_key=True, serialize=False)),
                ('wilaya_nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionMeteoWilayas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperateur', models.IntegerField()),
                ('vitesse_vent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('precepitation', models.IntegerField()),
                ('humidite', models.IntegerField()),
                ('icon', models.CharField(choices=[('pluvieux', 'pluie'), ('ensoleille', 'ensoleille'), ('nuageux', 'nuageux')], default='ensoleille')),
                ('wilaya_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meteo.wilaya')),
            ],
        ),
    ]
