# Generated by Django 5.0.2 on 2024-04-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0002_wilaya_conditionmeteowilayas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='Lieu',
            field=models.CharField(max_length=100),
        ),
    ]
